package com.test.instafeed.ui.theme

import androidx.compose.ui.graphics.Color

object LightColors {
    val primaryLight = Color(0xFF456731)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFFC5EFAA)
    val onPrimaryContainerLight = Color(0xFF082100)
    val secondaryLight = Color(0xFF55624C)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFD9E7CA)
    val onSecondaryContainerLight = Color(0xFF131F0D)
    val tertiaryLight = Color(0xFF386666)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFFBBEBEB)
    val onTertiaryContainerLight = Color(0xFF002020)
    val errorLight = Color(0xFFBA1A1A)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD6)
    val onErrorContainerLight = Color(0xFF410002)
    val backgroundLight = Color(0xFFF8FAF0)
    val onBackgroundLight = Color(0xFF191D16)
    val surfaceLight = Color(0xFFF8FAF0)
    val onSurfaceLight = Color(0xFF191D16)
    val surfaceVariantLight = Color(0xFFE0E4D6)
    val onSurfaceVariantLight = Color(0xFF43483E)
    val outlineLight = Color(0xFF74796D)
    val outlineVariantLight = Color(0xFFC3C8BB)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF2E312B)
    val inverseOnSurfaceLight = Color(0xFFF0F2E7)
    val inversePrimaryLight = Color(0xFFAAD290)
    val surfaceDimLight = Color(0xFFD9DBD1)
    val surfaceBrightLight = Color(0xFFF8FAF0)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFF2F5EA)
    val surfaceContainerLight = Color(0xFFEDEFE4)
    val surfaceContainerHighLight = Color(0xFFE7E9DF)
    val surfaceContainerHighestLight = Color(0xFFE1E4D9)
}

object DarkColors {
    val primaryDark = Color(0xFFFFB5A0)
    val onPrimaryDark = Color(0xFF561F0F)
    val primaryContainerDark = Color(0xFF723523)
    val onPrimaryContainerDark = Color(0xFFFFDBD1)
    val secondaryDark = Color(0xFFE7BDB2)
    val onSecondaryDark = Color(0xFF442A22)
    val secondaryContainerDark = Color(0xFF5D4037)
    val onSecondaryContainerDark = Color(0xFFFFDBD1)
    val tertiaryDark = Color(0xFFD8C58D)
    val onTertiaryDark = Color(0xFF3B2F05)
    val tertiaryContainerDark = Color(0xFF534619)
    val onTertiaryContainerDark = Color(0xFFF5E1A7)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF690005)
    val errorContainerDark = Color(0xFF93000A)
    val onErrorContainerDark = Color(0xFFFFDAD6)
    val backgroundDark = Color(0xFF1A110F)
    val onBackgroundDark = Color(0xFFF1DFDA)
    val surfaceDark = Color(0xFF1A110F)
    val onSurfaceDark = Color(0xFFF1DFDA)
    val surfaceVariantDark = Color(0xFF53433F)
    val onSurfaceVariantDark = Color(0xFFD8C2BC)
    val outlineDark = Color(0xFFA08C87)
    val outlineVariantDark = Color(0xFF53433F)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFF1DFDA)
    val inverseOnSurfaceDark = Color(0xFF392E2B)
    val inversePrimaryDark = Color(0xFF8F4C38)
    val surfaceDimDark = Color(0xFF1A110F)
    val surfaceBrightDark = Color(0xFF423734)
    val surfaceContainerLowestDark = Color(0xFF140C0A)
    val surfaceContainerLowDark = Color(0xFF231917)
    val surfaceContainerDark = Color(0xFF271D1B)
    val surfaceContainerHighDark = Color(0xFF322825)
    val surfaceContainerHighestDark = Color(0xFF3D322F)
    val customColor1Dark = Color(0xFF2C2D30)
    val customColor2Dark = Color(0xFFFFCC02)
    //more colors.....
}